[package]
name = "arboard_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.3.0"
device_query = "0.2.8"
rodio = "0.17.1"